export declare type DYNAMIC_GLOBAL_PROPERTIES = {
  head_block_number:                           number
  head_block_id:                               string
  time:                                        string
  current_witness:                             string
  total_pow:                                   number
  num_pow_witnesses:                           number
  virtual_supply:                              string
  current_supply:                              string
  init_hbd_supply:                             string
  current_hbd_supply:                          string
  total_vesting_fund_hive:                     string
  total_vesting_shares:                        string
  total_reward_fund_hive:                      string
  total_reward_shares2:                        string
  pending_rewarded_vesting_shares:             string
  pending_rewarded_vesting_hive:               string
  hbd_interest_rate:                           number
  hbd_print_rate:                              number
  maximum_block_size:                          number
  required_actions_partition_percent:          number
  current_aslot:                               number
  recent_slots_filled:                         string
  participation_count:                         number
  last_irreversible_block_num:                 number
  vote_power_reserve_rate:                     number
  delegation_return_period:                    number
  reverse_auction_seconds:                     number
  available_account_subsidies:                 number
  hbd_stop_percent:                            number
  hbd_start_percent:                           number
  next_maintenance_time:                       string
  last_budget_time:                            string
  next_daily_maintenance_time:                 string
  content_reward_percent:                      number
  vesting_reward_percent:                      number
  sps_fund_percent:                            number
  sps_interval_ledger:                         string
  downvote_pool_percent:                       number
  current_remove_threshold:                    number
  early_voting_seconds:                        number
  mid_voting_seconds:                          number
  max_consecutive_recurrent_transfer_failures: number
  max_recurrent_transfer_end_date:             number
  min_recurrent_transfers_recurrence:          number
  max_open_recurrent_transfers:                number
}