export declare type GET_CONFIG = {
  HIVE_CHAIN_ID:                                    string
  HIVE_TREASURY_ACCOUNT:                            string
  IS_TEST_NET:                                      boolean
  HIVE_ENABLE_SMT:                                  boolean
  HIVE_BLOCKCHAIN_VERSION:                          string
  HIVE_INIT_PUBLIC_KEY_STR:                         string
  STEEM_CHAIN_ID:                                   string
  HIVE_ADDRESS_PREFIX:                              string
  HIVE_GENESIS_TIME:                                string
  HIVE_MINING_TIME:                                 string
  HIVE_CASHOUT_WINDOW_SECONDS_PRE_HF12:             number
  HIVE_CASHOUT_WINDOW_SECONDS_PRE_HF17:             number
  HIVE_CASHOUT_WINDOW_SECONDS:                      number
  HIVE_SECOND_CASHOUT_WINDOW:                       number
  HIVE_MAX_CASHOUT_WINDOW_SECONDS:                  number
  HIVE_UPVOTE_LOCKOUT_HF7:                          number
  HIVE_UPVOTE_LOCKOUT_SECONDS:                      number
  HIVE_UPVOTE_LOCKOUT_HF17:                         string
  HIVE_MIN_ACCOUNT_CREATION_FEE:                    number
  HIVE_MAX_ACCOUNT_CREATION_FEE:                    number
  HIVE_OWNER_AUTH_RECOVERY_PERIOD:                  string
  HIVE_ACCOUNT_RECOVERY_REQUEST_EXPIRATION_PERIOD:  string
  HIVE_OWNER_UPDATE_LIMIT:                          number
  HIVE_OWNER_AUTH_HISTORY_TRACKING_START_BLOCK_NUM: number
  HIVE_INIT_SUPPLY:                                 number
  HIVE_HBD_INIT_SUPPLY:                             number
  HIVE_PROPOSAL_MAINTENANCE_PERIOD:                 number
  HIVE_PROPOSAL_MAINTENANCE_CLEANUP:                number
  HIVE_DAILY_PROPOSAL_MAINTENANCE_PERIOD:           number
  HIVE_GOVERNANCE_VOTE_EXPIRATION_PERIOD:           string
  HIVE_GLOBAL_REMOVE_THRESHOLD:                     number
  HIVE_START_MINER_VOTING_BLOCK:                    number
  HIVE_DELAYED_VOTING_TOTAL_INTERVAL_SECONDS:       number
  HIVE_DELAYED_VOTING_INTERVAL_SECONDS:             number
  VESTS_SYMBOL: {
      nai:      string
      decimals: number
  },
  HIVE_SYMBOL: {
      nai:      string
      decimals: number
  },
  HBD_SYMBOL: {
      nai:      string
      decimals: number
  },
  HIVE_BLOCKCHAIN_HARDFORK_VERSION:                 string
  HIVE_100_PERCENT:                                 number
  HIVE_1_PERCENT:                                   number
  HIVE_1_BASIS_POINT:                               number
  HIVE_BLOCK_INTERVAL:                              number
  HIVE_BLOCKS_PER_YEAR:                             number
  HIVE_BLOCKS_PER_DAY:                              number
  HIVE_START_VESTING_BLOCK:                         number
  HIVE_INIT_MINER_NAME:                             string
  HIVE_NUM_INIT_MINERS:                             number
  HIVE_INIT_TIME:                                   string
  HIVE_MAX_WITNESSES:                               number
  HIVE_MAX_VOTED_WITNESSES_HF0:                     number
  HIVE_MAX_MINER_WITNESSES_HF0:                     number
  HIVE_MAX_RUNNER_WITNESSES_HF0:                    number
  HIVE_MAX_VOTED_WITNESSES_HF17:                    number
  HIVE_MAX_MINER_WITNESSES_HF17:                    number
  HIVE_MAX_RUNNER_WITNESSES_HF17:                   number
  HIVE_HARDFORK_REQUIRED_WITNESSES:                 number
  HIVE_MAX_TIME_UNTIL_EXPIRATION:                   number
  HIVE_MAX_MEMO_SIZE:                               number
  HIVE_MAX_PROXY_RECURSION_DEPTH:                   number
  HIVE_VESTING_WITHDRAW_INTERVALS_PRE_HF_16:        number
  HIVE_VESTING_WITHDRAW_INTERVALS:                  number
  HIVE_VESTING_WITHDRAW_INTERVAL_SECONDS:           number
  HIVE_MAX_WITHDRAW_ROUTES:                         number
  HIVE_MAX_PENDING_TRANSFERS:                       number
  HIVE_MAX_OPEN_RECURRENT_TRANSFERS:                number
  HIVE_MAX_CONSECUTIVE_RECURRENT_TRANSFER_FAILURES: number
  HIVE_MAX_RECURRENT_TRANSFER_END_DATE:             number
  HIVE_MAX_RECURRENT_TRANSFERS_PER_BLOCK:           number
  HIVE_MIN_RECURRENT_TRANSFERS_RECURRENCE:          number
  HIVE_SAVINGS_WITHDRAW_TIME:                       string
  HIVE_SAVINGS_WITHDRAW_REQUEST_LIMIT:              number
  HIVE_VOTING_MANA_REGENERATION_SECONDS:            number
  HIVE_MAX_VOTE_CHANGES:                            number
  HIVE_REVERSE_AUCTION_WINDOW_SECONDS_HF6:          number
  HIVE_REVERSE_AUCTION_WINDOW_SECONDS_HF20:         number
  HIVE_REVERSE_AUCTION_WINDOW_SECONDS_HF21:         number
  HIVE_EARLY_VOTING_SECONDS_HF25:                   number
  HIVE_MID_VOTING_SECONDS_HF25:                     number
  HIVE_MIN_VOTE_INTERVAL_SEC:                       number
  HIVE_VOTE_DUST_THRESHOLD:                         number
  HIVE_DOWNVOTE_POOL_PERCENT_HF21:                  number
  HIVE_MIN_ROOT_COMMENT_INTERVAL:                   number
  HIVE_MIN_REPLY_INTERVAL:                          number
  HIVE_MIN_REPLY_INTERVAL_HF20:                     number
  HIVE_MIN_COMMENT_EDIT_INTERVAL:                   number
  HIVE_POST_AVERAGE_WINDOW:                         number
  HIVE_POST_WEIGHT_CONSTANT:                        number
  HIVE_MAX_ACCOUNT_WITNESS_VOTES:                   number
  HIVE_DEFAULT_HBD_INTEREST_RATE:                   number
  HIVE_INFLATION_RATE_START_PERCENT:                number
  HIVE_INFLATION_RATE_STOP_PERCENT:                 number
  HIVE_INFLATION_NARROWING_PERIOD:                  number
  HIVE_CONTENT_REWARD_PERCENT_HF16:                 number
  HIVE_VESTING_FUND_PERCENT_HF16:                   number
  HIVE_PROPOSAL_FUND_PERCENT_HF0:                   number
  HIVE_CONTENT_REWARD_PERCENT_HF21:                 number
  HIVE_PROPOSAL_FUND_PERCENT_HF21:                  number
  HIVE_HF21_CONVERGENT_LINEAR_RECENT_CLAIMS:        string
  HIVE_CONTENT_CONSTANT_HF21:                       string
  HIVE_MINER_PAY_PERCENT:                           number
  HIVE_MAX_RATION_DECAY_RATE:                       number
  HIVE_BANDWIDTH_AVERAGE_WINDOW_SECONDS:            number
  HIVE_BANDWIDTH_PRECISION:                         number
  HIVE_MAX_COMMENT_DEPTH_PRE_HF17:                  number
  HIVE_MAX_COMMENT_DEPTH:                           number
  HIVE_SOFT_MAX_COMMENT_DEPTH:                      number
  HIVE_MAX_RESERVE_RATIO:                           number
  HIVE_CREATE_ACCOUNT_WITH_HIVE_MODIFIER:           number
  HIVE_CREATE_ACCOUNT_DELEGATION_RATIO:             number
  HIVE_CREATE_ACCOUNT_DELEGATION_TIME:              string
  HIVE_MINING_REWARD: {
      amount:    string
      precision: number
      nai:       string
  },
  HIVE_EQUIHASH_N:                                  number
  HIVE_EQUIHASH_K:                                  number
  HIVE_LIQUIDITY_TIMEOUT_SEC:                       string
  HIVE_MIN_LIQUIDITY_REWARD_PERIOD_SEC:             number
  HIVE_LIQUIDITY_REWARD_PERIOD_SEC:                 number
  HIVE_LIQUIDITY_REWARD_BLOCKS:                     number
  HIVE_MIN_LIQUIDITY_REWARD: {
    amount:    string
    precision: number
    nai:       string
  },
  HIVE_MIN_CONTENT_REWARD: {
    amount:    string
    precision: number
    nai:       string
  },
  HIVE_MIN_CURATE_REWARD: {
    amount:    string
    precision: number
    nai:       string
  },
  HIVE_MIN_PRODUCER_REWARD: {
    amount:    string
    precision: number
    nai:       string
  },
  HIVE_MIN_POW_REWARD: {
    amount:    string
    precision: number
    nai:       string
  },
  HIVE_ACTIVE_CHALLENGE_FEE: {
    amount:    string
    precision: number
    nai:       string
  },
  HIVE_OWNER_CHALLENGE_FEE: {
    amount:    string
    precision: number
    nai:       string
  },
  HIVE_ACTIVE_CHALLENGE_COOLDOWN:              string
  HIVE_OWNER_CHALLENGE_COOLDOWN:               string
  HIVE_POST_REWARD_FUND_NAME:                  string
  HIVE_COMMENT_REWARD_FUND_NAME:               string
  HIVE_RECENT_RSHARES_DECAY_TIME_HF17:         string
  HIVE_RECENT_RSHARES_DECAY_TIME_HF19:         string
  HIVE_CONTENT_CONSTANT_HF0:                   string
  HIVE_APR_PERCENT_MULTIPLY_PER_BLOCK:         string
  HIVE_APR_PERCENT_SHIFT_PER_BLOCK:            number
  HIVE_APR_PERCENT_MULTIPLY_PER_ROUND:         string
  HIVE_APR_PERCENT_SHIFT_PER_ROUND:            number
  HIVE_APR_PERCENT_MULTIPLY_PER_HOUR:          string
  HIVE_APR_PERCENT_SHIFT_PER_HOUR:             number
  HIVE_CURATE_APR_PERCENT:                     number
  HIVE_CONTENT_APR_PERCENT:                    number
  HIVE_LIQUIDITY_APR_PERCENT:                  number
  HIVE_PRODUCER_APR_PERCENT:                   number
  HIVE_POW_APR_PERCENT:                        number
  HIVE_MIN_PAYOUT_HBD: {
    amount:    string
    precision: number
    nai:       string
  },
  HIVE_HBD_STOP_PERCENT_HF14:                  number
  HIVE_HBD_STOP_PERCENT_HF20:                  number
  HIVE_HBD_START_PERCENT_HF14:                 number
  HIVE_HBD_START_PERCENT_HF20:                 number
  HIVE_MIN_ACCOUNT_NAME_LENGTH:                number
  HIVE_MAX_ACCOUNT_NAME_LENGTH:                number
  HIVE_MIN_PERMLINK_LENGTH:                    number
  HIVE_MAX_PERMLINK_LENGTH:                    number
  HIVE_MAX_WITNESS_URL_LENGTH:                 number
  HIVE_MAX_SHARE_SUPPLY:                       string
  HIVE_MAX_SATOSHIS:                           string
  HIVE_MAX_SIG_CHECK_DEPTH:                    number
  HIVE_MAX_SIG_CHECK_ACCOUNTS:                 number
  HIVE_MIN_TRANSACTION_SIZE_LIMIT:             number
  HIVE_SECONDS_PER_YEAR:                       number
  HIVE_HBD_INTEREST_COMPOUND_INTERVAL_SEC:     number
  HIVE_MAX_TRANSACTION_SIZE:                   number
  HIVE_MIN_BLOCK_SIZE_LIMIT:                   number
  HIVE_MAX_BLOCK_SIZE:                         number
  HIVE_SOFT_MAX_BLOCK_SIZE:                    number
  HIVE_MIN_BLOCK_SIZE:                         number
  HIVE_BLOCKS_PER_HOUR:                        number
  HIVE_FEED_INTERVAL_BLOCKS:                   number
  HIVE_FEED_HISTORY_WINDOW_PRE_HF_16:          number
  HIVE_FEED_HISTORY_WINDOW:                    number
  HIVE_MAX_FEED_AGE_SECONDS:                   number
  HIVE_MIN_FEEDS:                              number
  HIVE_CONVERSION_DELAY_PRE_HF_16:             string
  HIVE_CONVERSION_DELAY:                       string
  HIVE_COLLATERALIZED_CONVERSION_DELAY:        string
  HIVE_CONVERSION_COLLATERAL_RATIO:            number
  HIVE_COLLATERALIZED_CONVERSION_FEE:          number
  HIVE_MIN_UNDO_HISTORY:                       number
  HIVE_MAX_UNDO_HISTORY:                       number
  HIVE_MIN_TRANSACTION_EXPIRATION_LIMIT:       number
  HIVE_BLOCKCHAIN_PRECISION:                   number
  HIVE_BLOCKCHAIN_PRECISION_DIGITS:            number
  HIVE_MAX_INSTANCE_ID:                        string
  HIVE_MAX_AUTHORITY_MEMBERSHIP:               number
  HIVE_MAX_ASSET_WHITELIST_AUTHORITIES:        number
  HIVE_MAX_URL_LENGTH:                         number
  HIVE_IRREVERSIBLE_THRESHOLD:                 number
  HIVE_VIRTUAL_SCHEDULE_LAP_LENGTH:            string
  HIVE_VIRTUAL_SCHEDULE_LAP_LENGTH2:           string
  HIVE_INITIAL_VOTE_POWER_RATE:                number
  HIVE_REDUCED_VOTE_POWER_RATE:                number
  HIVE_MAX_LIMIT_ORDER_EXPIRATION:             number
  HIVE_DELEGATION_RETURN_PERIOD_HF0:           number
  HIVE_DELEGATION_RETURN_PERIOD_HF20:          number
  HIVE_RD_MIN_DECAY_BITS:                      number
  HIVE_RD_MAX_DECAY_BITS:                      number
  HIVE_RD_DECAY_DENOM_SHIFT:                   number
  HIVE_RD_MAX_POOL_BITS:                       number
  HIVE_RD_MAX_BUDGET_1:                        string
  HIVE_RD_MAX_BUDGET_2:                        number
  HIVE_RD_MAX_BUDGET_3:                        number
  HIVE_RD_MAX_BUDGET:                          number
  HIVE_RD_MIN_DECAY:                           number
  HIVE_RD_MIN_BUDGET:                          number
  HIVE_RD_MAX_DECAY:                           number
  HIVE_ACCOUNT_SUBSIDY_PRECISION:              number
  HIVE_WITNESS_SUBSIDY_BUDGET_PERCENT:         number
  HIVE_WITNESS_SUBSIDY_DECAY_PERCENT:          number
  HIVE_DEFAULT_ACCOUNT_SUBSIDY_DECAY:          number
  HIVE_DEFAULT_ACCOUNT_SUBSIDY_BUDGET:         number
  HIVE_DECAY_BACKSTOP_PERCENT:                 number
  HIVE_BLOCK_GENERATION_POSTPONED_TX_LIMIT:    number
  HIVE_PENDING_TRANSACTION_EXECUTION_LIMIT:    number
  HIVE_CUSTOM_OP_ID_MAX_LENGTH:                number
  HIVE_CUSTOM_OP_DATA_MAX_LENGTH:              number
  HIVE_BENEFICIARY_LIMIT:                      number
  HIVE_COMMENT_TITLE_LIMIT:                    number
  HIVE_ONE_DAY_SECONDS:                        number
  HIVE_MINER_ACCOUNT:                          string
  HIVE_NULL_ACCOUNT:                           string
  HIVE_TEMP_ACCOUNT:                           string
  HIVE_PROXY_TO_SELF_ACCOUNT:                  string
  HIVE_ROOT_POST_PARENT:                       string
  OBSOLETE_TREASURY_ACCOUNT:                   string
  NEW_HIVE_TREASURY_ACCOUNT:                   string
  HIVE_TREASURY_FEE:                           number
  HIVE_PROPOSAL_SUBJECT_MAX_LENGTH:            number
  HIVE_PROPOSAL_MAX_IDS_NUMBER:                number
  HIVE_PROPOSAL_FEE_INCREASE_DAYS:             number
  HIVE_PROPOSAL_FEE_INCREASE_DAYS_SEC:         number
  HIVE_PROPOSAL_FEE_INCREASE_AMOUNT:           number
  HIVE_PROPOSAL_CONVERSION_RATE:               number
}